# Generated by Django 4.0.5 on 2022-07-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
