# Generated by Django 4.0.5 on 2022-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_docs_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='name',
            new_name='visitor_name',
        ),
        migrations.AddField(
            model_name='data',
            name='response',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
